version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - linebreak
  - middlewares
  - OIDS
  - openapi
  - popd
  - pushd
  - signin
  - webfonts
ignoreWords: []
import: []
