service: simple-idp

provider:
  name: aws
  runtime: nodejs18.x

custom:
  domainName: simple-idp.click # By Route53 Registrar
  # cSpell: disable-next-line
  rootDomainHostedZoneID: Z05506703IRO74FTLWKH9 # Created by Route53 Registrar
  loginRedirectURI: http://localhost

resources:
  Resources:
    WildDomainCertificate:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: '*.${self:custom.domainName}'
        ValidationMethod: DNS
        DomainValidationOptions:
          - DomainName: ${self:custom.domainName}
            HostedZoneId: ${self:custom.rootDomainHostedZoneID}

    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        Schema:
          - Name: email
            Required: true
            Mutable: false
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        UsernameAttributes: ['email']
        AutoVerifiedAttributes: ['email']
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_LINK
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
    UserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        UserPoolId: !Ref UserPool
        Domain: auth.${self:custom.domainName}
        CustomDomainConfig:
          CertificateArn: !Ref WildDomainCertificate
    UserPoolCustomDomainRecordSetGroup:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId: ${self:custom.rootDomainHostedZoneID}
        RecordSets:
          - Name: auth.${self:custom.domainName}
            Type: A
            AliasTarget:
              DNSName: !GetAtt UserPoolDomain.CloudFrontDistribution
              # Fixed value to target CloudFront Distribution
              # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget-1.html#cfn-route53-aliastarget-hostedzoneid
              # cSpell: disable-next-line
              HostedZoneId: Z2FDTNDATAQYW2
    FacebookIdentityProvider:
      Type: AWS::Cognito::UserPoolIdentityProvider
      Properties:
        UserPoolId: !Ref UserPool
        ProviderName: Facebook
        ProviderType: Facebook
        ProviderDetails:
          client_id: ${ssm:simple-idp.facebook.clientID}
          client_secret: ${ssm:simple-idp.facebook.clientSecret}
          authorize_scopes: public_profile,email
          # api_version: 2.12
        AttributeMapping:
          email: email
    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref UserPool
        GenerateSecret: false
        CallbackURLs:
          - ${self:custom.loginRedirectURI}
        DefaultRedirectURI: ${self:custom.loginRedirectURI}
        PreventUserExistenceErrors: ENABLED
        AllowedOAuthFlows:
          - code
        AllowedOAuthScopes:
          - email
          - phone
          - openid
        SupportedIdentityProviders:
          - COGNITO
          # - Google
          - Facebook